apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tentacle
  name: tentacle
  namespace: support
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tentacle
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tentacle
    spec:
      containers:
      - env:
        - name: serverUrl
          value: 
        - name: apiKey
          value: 
        - name: workerPool
          value: 
        image: 
        imagePullPolicy: Always
        name: tentacle-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: github-tentacle
      dnsPolicy: ClusterFirst
      hostname: kube-tentacle
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
