name: Build and Push
on:
  push:
    branches:
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: enosix/github-action-generate-semver@v1.1
          id: version
          with:
            bump: patch
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: enosix/docker-sfdx/sfdx
            registry: docker.pkg.github.com
            tags: ${{ steps.version.outputs.version }}
            tag_with_ref: true
            tag_with_sha: true
