name: Build and Push
on:
  push:
    branches:
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: docker.pkg.github.com/enosix/docker-sfdx/sfdx
            registry: ghcr.io
            tag_with_ref: true
